In [1]:
import numpy as np
data = np.random.randint(10,50,size=(24,24))
print(data)

[[27 49 17 44 17 20 31 23 34 47 26 16 38 39 26 48 36 49 27 39 10 30 49 40]
 [30 30 21 32 11 12 16 12 48 37 49 14 33 41 30 26 34 35 19 48 17 23 40 41]
 [30 18 26 37 39 28 12 26 32 39 13 36 34 22 33 40 19 36 10 30 39 34 12 26]
 [41 25 29 31 29 37 45 11 43 34 33 39 15 35 41 15 40 28 48 43 49 24 18 33]
 [22 25 18 38 29 44 40 14 11 34 26 24 47 40 14 41 43 39 35 22 13 23 10 30]
 [10 44 28 14 20 47 16 11 20 21 15 24 31 29 16 20 36 43 15 49 23 13 35 22]
 [21 45 38 38 19 39 32 10 30 38 19 24 34 20 35 39 14 38 40 42 16 48 32 29]
 [48 47 29 28 21 46 37 41 25 41 32 20 17 44 40 33 36 31 18 27 44 30 40 11]
 [46 26 44 38 15 43 10 40 25 30 44 32 15 21 30 47 28 11 40 13 18 37 35 40]
 [37 24 17 28 48 24 36 20 20 10 15 11 38 25 13 12 31 20 47 45 23 17 26 23]
 [25 41 35 23 32 12 39 28 21 48 15 32 15 48 22 10 43 46 49 24 44 39 36 35]
 [12 33 27 40 37 46 19 46 11 38 15 19 17 26 20 32 22 46 26 15 36 32 44 36]
 [15 30 21 24 15 13 23 23 24 17 41 16 31 30 46 24 49 40 37 38 13 42 38 18]
 [40 45 10 24 25 41 23 26

In [4]:
data_3d=data.reshape(3,8,24)
print(data_3d)

[[[27 49 17 44 17 20 31 23 34 47 26 16 38 39 26 48 36 49 27 39 10 30 49
   40]
  [30 30 21 32 11 12 16 12 48 37 49 14 33 41 30 26 34 35 19 48 17 23 40
   41]
  [30 18 26 37 39 28 12 26 32 39 13 36 34 22 33 40 19 36 10 30 39 34 12
   26]
  [41 25 29 31 29 37 45 11 43 34 33 39 15 35 41 15 40 28 48 43 49 24 18
   33]
  [22 25 18 38 29 44 40 14 11 34 26 24 47 40 14 41 43 39 35 22 13 23 10
   30]
  [10 44 28 14 20 47 16 11 20 21 15 24 31 29 16 20 36 43 15 49 23 13 35
   22]
  [21 45 38 38 19 39 32 10 30 38 19 24 34 20 35 39 14 38 40 42 16 48 32
   29]
  [48 47 29 28 21 46 37 41 25 41 32 20 17 44 40 33 36 31 18 27 44 30 40
   11]]

 [[46 26 44 38 15 43 10 40 25 30 44 32 15 21 30 47 28 11 40 13 18 37 35
   40]
  [37 24 17 28 48 24 36 20 20 10 15 11 38 25 13 12 31 20 47 45 23 17 26
   23]
  [25 41 35 23 32 12 39 28 21 48 15 32 15 48 22 10 43 46 49 24 44 39 36
   35]
  [12 33 27 40 37 46 19 46 11 38 15 19 17 26 20 32 22 46 26 15 36 32 44
   36]
  [15 30 21 24 15 13 23 23 24 17 41 16 31 30 46 24

In [5]:
threshold = 40

In [6]:
mask = data_3d>threshold
print(mask)

[[[False  True False  True False False False False False  True False
   False False False False  True False  True False False False False
    True False]
  [False False False False False False False False  True False  True
   False False  True False False False False False  True False False
   False  True]
  [False False False False False False False False False False False
   False False False False False False False False False False False
   False False]
  [ True False False False False False  True False  True False False
   False False False  True False False False  True  True  True False
   False False]
  [False False False False False  True False False False False False
   False  True False False  True  True False False False False False
   False False]
  [False  True False False False  True False False False False False
   False False False False False False  True False  True False False
   False False]
  [False  True False False False False False False False False False
   Fals

In [7]:
avg_temp = data_3d.mean()
print(avg_temp)

29.60763888888889


In [8]:
data_3d[mask]= avg_temp
print("reshaped 3D data:\n",data_3d)
print("\nAverage Temperatue:",avg_temp)

reshaped 3D data:
 [[[27 29 17 29 17 20 31 23 34 29 26 16 38 39 26 29 36 29 27 39 10 30 29
   40]
  [30 30 21 32 11 12 16 12 29 37 29 14 33 29 30 26 34 35 19 29 17 23 40
   29]
  [30 18 26 37 39 28 12 26 32 39 13 36 34 22 33 40 19 36 10 30 39 34 12
   26]
  [29 25 29 31 29 37 29 11 29 34 33 39 15 35 29 15 40 28 29 29 29 24 18
   33]
  [22 25 18 38 29 29 40 14 11 34 26 24 29 40 14 29 29 39 35 22 13 23 10
   30]
  [10 29 28 14 20 29 16 11 20 21 15 24 31 29 16 20 36 29 15 29 23 13 35
   22]
  [21 29 38 38 19 39 32 10 30 38 19 24 34 20 35 39 14 38 40 29 16 29 32
   29]
  [29 29 29 28 21 29 37 29 25 29 32 20 17 29 40 33 36 31 18 27 29 30 40
   11]]

 [[29 26 29 38 15 29 10 40 25 30 29 32 15 21 30 29 28 11 40 13 18 37 35
   40]
  [37 24 17 28 29 24 36 20 20 10 15 11 38 25 13 12 31 20 29 29 23 17 26
   23]
  [25 29 35 23 32 12 39 28 21 29 15 32 15 29 22 10 29 29 29 24 29 39 36
   35]
  [12 33 27 40 37 29 19 29 11 38 15 19 17 26 20 32 22 29 26 15 36 32 29
   36]
  [15 30 21 24 15 13 23 23 24 1